import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { AuthProvider, useAuth } from "@/component/AuthContext";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};


function AuthBar() {
  const { user, signIn, signOut } = useAuth()
  return (
    <div className="flex justify-end items-center gap-2 p-2 border-b bg-white">
      {user ? (
        <>
          <span className="text-sm">{user.displayName || user.email}</span>
          <button className="px-2 py-1 text-xs bg-gray-200 rounded" onClick={signOut}>Sign Out</button>
        </>
      ) : (
        <button className="px-2 py-1 text-xs bg-blue-600 text-white rounded" onClick={signIn}>Sign In with Google</button>
      )}
    </div>
  )
}

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable} antialiased`}>
        <AuthProvider>
          <AuthBar />
          {children}
        </AuthProvider>
      </body>
    </html>
  )
}
